Repository jaoafa/jaoweb4, pull requests merged in 2023-06, with the labels that each got.

#129 ci: fix cloudflare/pages-action get ref
  .github/workflows/publish.yml
Labels: 🚀request-deploy

#126 プロフィールページを更新
  src/content/4.support/3.profiles.md
Labels: 📝documentation

#128 FAQページの文章を、旧サイトから移植
  src/content/4.support/2.faq.md
Labels: 📝documentation

#157 fix:FAQ内の項目について、重複している部分を削除
  src/content/4.support/2.faq.md
Labels: 📝documentation

#156 サーバ仕様のページを作成
  src/content/2.docs/1.spec.md
Labels: 📝documentation

#164 fix: typo in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: 📝documentation, 🐛bug

#119 feat: ルール群の作成および更新
  src/content/2.docs/1.rules/1.build.md
  src/content/2.docs/1.rules/index.md
Labels: 📝documentation

#166 ci: autofixのワークフローを追加
  .github/workflows/autofix.yml
Labels: ♻improvement

#168 docs: 運営者情報ページの各ユーザ情報の表示を変更
  src/components/content/ContentUser.vue
  src/content/4.support/3.profiles.md
Labels: 📝documentation
